/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

import Queue.Queue;
import Stacks.Stack;

public class Library {
    public static void main(String[] args) throws Exception {
        queueDemo();
        stackDemo();
    }

    public static void queueDemo() throws Exception {
        Queue queue = new Queue();

        queue.enqueue("F");
        queue.enqueue("A");
        queue.enqueue("R");
        queue.enqueue("A");
        queue.enqueue("H");

        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println("The front of the Queue is => " + queue.peek());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
    }

    public static void stackDemo() throws Exception {
        Stack stack = new Stack();

        stack.push("A");
        stack.push("H");
        stack.push("M");
        stack.push("A");
        stack.push("D");

        System.out.println("The top of the stack is => " + stack.peek());

        System.out.println(stack.pop());

        System.out.println("The top of the stack is => " + stack.peek());

        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
    }
}